apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      component: registry
  template:
    metadata:
      labels:
        component: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5555