apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          imagePullPolicy: Never
          image: localhost:5000/us-project_client
          ports:
            - containerPort: 3000
